@appUrl= http://localhost:5247
@daprUrl= http://localhost:3510

### List all customers
GET {{appUrl}}/customer

### Create a customer
POST {{appUrl}}/customer
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@lovelace.com"
}

### Retrieve a customer
@email=ada@lovelace.com
GET {{appUrl}}/customer/{{email}}