@appUrl= http://localhost:5247
@daprUrl= http://localhost:3510

POST {{appUrl}}/customer
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@jd.com"
}

###

@email=j@jd.com
GET {{appUrl}}/customer/{{email}}