@appUrl= http://localhost:5249
@daprUrl= http://localhost:3512

### List all products
GET {{appUrl}}/product

### Create a product
POST {{appUrl}}/product
Content-Type: application/json

{
  "name": "Paid plan"
}

### Retrieve a product
@name="Paid plan"
GET {{appUrl}}/product/{{name}}