@appUrl= http://localhost:5253
@daprUrl= http://localhost:3516

### Setup Stripe
# @name setupstripeRequest
POST {{appUrl}}/setupstripe
Content-Type: application/json

{
    "customerName": "Ada Lovelace",
    "customerEmail": "ada@lovelace.org",
    "meterName": "Calculation API",
    "meterEventName": "calculation_executed",
    "productPrices": [
        {
            "productName": "Paid plan",
            "priceLookupKey": "paid_calculation_usage",
            "unitAmount": 5
        },
        {
            "productName": "Free plan",
            "priceLookupKey": "free_calculation_usage",
            "unitAmount": 0
        }
    ]
}

### GET workflow status directly via the Dapr HTTP API
@instanceId={{setupstripeRequest.response.headers.Location}}
GET {{daprUrl}}/v1.0/workflows/dapr/{{instanceId}}